### ISSUE TITLE
german listing not working properly

### ISSUE THREAD

**Issue by BSlGuru** [todordev/Vip-Amazon-Associates#1]
Hello I have a problem. normally the VIP Amazon Module should show small pics if the items and price etc. 
But it doesnt work for the german amazon site, because ther are only text links shown an no items. is this a bug of your Mod?
(www.el-guru.de)

**Comment by todordev** [comment]
Could you try the new version?
http://itprism.com/free-joomla-extensions/ecommerce-gamification/amazon-associate-affiliate
