### ISSUE TITLE
Page Title Keyword Failure with Joomla 3.3.1

### ISSUE THREAD

**Issue by vasbinde** [todordev/Vip-Amazon-Associates#4]
I have installed the latest VIP Amazon Associates on a site running Joomla 3.3.1.  When I attempt to use the Filter option of "Page Title".  It fails and breaks the entire page with the following error:  

Fatal error: Call to undefined method JApplicationSite::getPageTitle() in /home/sitename/public_html/modules/mod_vipamazonassociates/helper.php on line 43

My guess is that the method getPageTitle was removed from the JApplicationSite API in Joomla 3.2 or perhaps 3.3.

Can this be corrected?

Thanks!

**Comment by todordev** [comment]
Hi,
Thank you for the post!
I see. I am going to check it and fix it tomorrow.

Best regards,
Todor

**Comment by todordev** [comment]
fixed
