### ISSUE TITLE
The documentation and demo links are not working

### ISSUE THREAD

**Issue by ricoo123** [todordev/Vip-Amazon-Associates#6]
Hi,

The links to the documentation and to the demo are not working.

Could you show them please?

Thank you,
Rumen

**Comment by todordev** [comment]
Hi Rumen,
Thank you for the post! You are right. Amazon changes their services.
I am going to stop development of this extension. Sorry!

Regards,
T

**Comment by ricoo123** [comment]
OK, thank you.

Although it was a good idea.
